# Properties file for local/dev enviroment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties

spring:
  datasource:
    host: localhost:3306
    db: projeto_integrador
    username: root
    password:
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      sql: debug
      ddl-auto: update # create-drop para crear las entidades, una vez creadas y finalizado el mododel cambiar a none
    database-platform: org.hibernate.dialect.MySQL8Dialect


server:
  port: 8082 # no cambiar en prod