# Properties file for local/dev enviroment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties

spring:
  datasource:
    host: localhost:3306
    #    host: proxysql.master.meliseginf.com:6612
    db: ${SECRET_DATABASE}
    #    db: g3projdb
    username: ${SECRET_USER}
    password: ${SECRET_PASS}
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      sql: debug
      ddl-auto: update # create-drop para crear las entidades, una vez creadas y finalizado el mododel cambiar a none
    database-platform: org.hibernate.dialect.MySQL8Dialect


server:
  port: 8082 # no cambiar en prod